- name: Install k3s using k3sup
  hosts: k3s_control_plane[0]
  tasks:
    - name: Run k3sup install command
      delegate_to: localhost
      shell: >
        k3sup install --ip {{ ansible_host }} \
        --tls-san {{ hostvars['kube-vip']['ansible_host'] }} \
        --cluster \
        --context k3s-cluster-ha \
        --k3s-extra-args "--disable traefik --disable servicelb --node-ip={{ ansible_host }}" \
        --print-command
      register: k3sup_master
      changed_when: k3sup_master.stdout != ""
      failed_when: k3sup_master.stderr != ""
      check_mode: no
      tags:
        - k3sup-master

- name: Set KUBECONFIG environment variable
  hosts: kube-vip
  tasks:
    - name: Export KUBECONFIG
      shell: export KUBECONFIG={{ kubeconfig_path }}
      delegate_to: localhost

    - name: Update kubeconfig server address
      replace:
        path: "{{ kubeconfig_path }}"
        regexp: 'server: http://.*:6443'
        replace: "server: http://{{ hostvars['kube-vip']['ansible_host'] }}:6443"
      delegate_to: localhost