default:

terraform-plan:
	sh ./scripts/9001_k3s_control_plan.sh

terraform-apply:
	sh ./scripts/9001_k3s_control_apply.sh

terraform-destroy:
	sh ./scripts/9001_k3s_control_destroy.sh


clean:
	sh ./scripts/cleanup.sh