---
  - name: Install latest open-iscsi
    hosts: k3s_longhorn
    remote_user: "k3sadmin"
    vars_files:
      - ../secrets/vaults/harbourside.yml
    order: inventory
    serial: 1
    tasks:
      - name: Install open-iscsi
        apt:
          name: open-iscsi
          state: present
          update_cache: true
        become: true
