- name: Shutdown VMs in order
  hosts: test
  remote_user: k3sadmin
  become: true
  order: inventory
  serial: 1
  tasks:
    - name: Shutdown VM
      ansible.builtin.shell: shutdown -h now
      async: 1 # run the task in the background
      poll: 0 # don't wait for the task to complete