- name: Start VMs in order
  hosts: k3s
  remote_user: k3sadmin
  gather_facts: no
  order: inventory
  serial: 1
  vars_files:
    - ../secrets/vaults/harbourside.yml
  tasks:
    - name: Start VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ hostvars[inventory_hostname]['vm_id'] }}"
        state: started
      delegate_to: localhost