- name: Join the other Control nodes to k3s cluster
  hosts: k3s_control_plane:!k3s_control_plane[0]
  become: yes
  tasks:
    - name: Run k3sup join command
      delegate_to: localhost
      shell: >
           k3sup join \
           --ip {{ ansible_host }} \
           --user k3sadmin \
           --sudo \
           --k3s-channel stable \
           --server \
           --server-ip {{ hostvars['kube-vip']['ansible_host'] }} \
           --server-user k3sadmin \
           --sudo \
           --k3s-extra-args "--disable traefik  --disable servicelb --node-ip={{ ansible_host }}" \
           --print-command
      register: k3sup_control
      changed_when: k3sup_control.stdout != ""
      failed_when: k3sup_control.stderr != ""
      check_mode: no
      tags:
        - k3sup-control

# Breakdown of the arguments for joining the control nodes

# k3sup join: This command is used to join a new node to an existing k3s cluster.

# --ip {{ ansible_host }}: This specifies the IP address of the node that you want to join to the cluster, which is pulled from the hosts file.

# --user k3sadmin: This specifies the username to use when connecting to the node. Replace `k3sadmin` with your actual username.

# --sudo: This flag tells k3sup to use sudo when running commands on the node.

# --k3s-channel stabl`: This sets the version of k3s to install. The `stable` channel will install the latest stable release.

# --server: This flag tells k3sup that this node should be a server node. In k3s, server nodes run the Kubernetes control plane.

# --server-ip {{ hostvars['kube-vip']['ansible_host'] }}: This specifies the IP address of kube-vip that you set in your host file.

# --server-user k3sadmin: This specifies the username to use when connecting to the server. Replace `k3sadmin` with your actual username.

# --k3s-extra-args "--disable traefik  --disable servicelb --node-ip={{ ansible_host }}": This passes additional arguments to k3s. In this case, it disables the `traefik` and `servicelb` components and sets the node IP to `10.90.3.102`.

# This command will join a new server node to your k3s cluster, with the specified configuration.