- name: Install kube-vip RBAC manifest
  hosts: localhost
  vars:
    kubeconfig_path: /home/gavin/kubeconfig
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Apply kube-vip RBAC manifest
      k8s:
        src: https://kube-vip.io/manifests/rbac.yaml
        state: present

- name: SSH into k3s_control_plane[0] and setup kube-vip
  hosts: k3s_control_plane[0]
  become: yes
  tasks:
    - name: Pull kube-vip image
      ansible.builtin.command:
        cmd: ctr image pull docker.io/plndr/kube-vip:latest

    - name: Create alias for kube-vip
      ansible.builtin.shell:
        cmd: echo 'alias kube-vip="ctr run --rm --net-host docker.io/plndr/kube-vip:latest vip /kube-vip"' >> ~/.bashrc

    - name: Run kube-vip manifest daemonset
      shell: >
        kube-vip manifest daemonset \
        --arp \
        --interface eth0 \
        --address {{ hostvars['kube-vip']['ansible_host'] }} \
        --controlplane \
        --leaderElection \
        --inCluster | tee /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
      register: kube_vip_manifest_replicated
      changed_when: kube_vip_manifest.stdout != ""
      failed_when: kube_vip_manifest.stderr != ""
      check_mode: no
      tags:
        - kube-vip-manifest