---
- name: Setup Cifs share
  block:
    - name: cifs Utils Present
      ansible.builtin.package:
        name: cifs-utils
        state: present

    - name: check mountpoint exists
      ansible.builtin.file:
        path: "{{ mount_point }}"
        state: directory

    - name: Change directory permissions
      ansible.builtin.file:
        path: "{{ mount_point }}"
        mode: '0755'
        owner: k3sadmin
        group: k3sadmin
      ignore_errors: true
        
    - name: Check if network share is already mounted
      ansible.builtin.shell:
        cmd: mountpoint -q {{ mount_point }}
      register: result
      ignore_errors: true

    - name: Mount network share
      ansible.builtin.shell:
        cmd: >
          mount -t cifs {{ cifs_uri }} {{ mount_point }} -o username="{{ cifs_username }}",password="{{ cifs_password }}",vers=3.0
      when: result is failed

    - name: Add mount to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{ cifs_uri }} {{ mount_point }} cifs username={{ cifs_username }},password={{ cifs_password }},vers=3.0 0 0"
        state: present
      when: result is failed