---
- name: Packages
  block:
    - name: Packages | Install common packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - cifs-utils
          - conntrack
          - curl
          - dirmngr
          - docker.io
          - gdisk
          - git
          - gnupg
          - hdparm
          - htop
          - iperf3
          - iptables
          - iputils-ping
          - ipvsadm
          - libseccomp2
          - lm-sensors
          - neofetch
          - net-tools
          - nfs-common
          - nvme-cli
          - open-iscsi
          - parted
          - psmisc
          - python3
          - python3-pip
          - python-is-python3
          - python3-apt
          - python3-kubernetes
          - python3-yaml
          - smartmontools
          - socat
          - software-properties-common
          - unzip
          - util-linux
          #i965-va-driver-shaders,intel-gpu-tools,intel-media-va-driver-non-free,
        install_recommends: false

    - name: Install python3-openshift
      ansible.builtin.pip:
        name: openshift
        executable: pip3

- name: Install Helm
  block:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0700'

    - name: Run Helm install script
      command: /tmp/get-helm-3