# Boostrap K3S cluster
---
- hosts: k3s
  become: true
  vars_files:
  - ../secrets/vaults/harbourside.yml
  - ..vars/main.yaml
  remote_user: k3sadmin
  gather_facts: true

  pre_tasks:
    - name: Ping all hosts
      ping:

  roles:
    - k3s_node_provision
    - k3s_prerequisites
    - k3s_master
    - k3s_controllb
    - k3s_control
    - k3s_agents

  tasks:
  - name: Set hostname
    hostname:
      name: '{{ inventory_hostname }}'
