---
- name: Prepare System
  hosts: kubernetes
  remote_user: k3sadmin
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    cifs_uri: //10.90.100.1/kubeShare
    mount_point: "/mnt/kubeShare/"
    zsh_path: "/home/k3sadmin"
  vars_files:
    - ../../secrets/vaults/harbourside.yml
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Include packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/packages.yaml
      tags: ["packages"]

    - name: Include cifs task configuration.
      ansible.builtin.import_tasks:
        file: tasks/cifs.yaml
      tags: ["cifs"]

    - name: Setup Shell
      block:
        - name: Include fonts task configuration.
          ansible.builtin.import_tasks:
            file: tasks/fonts.yaml
          tags: ["fonts"]

        - name: Include ZSH task configuration.
          ansible.builtin.import_tasks:
            file: tasks/zsh.yaml
          tags: ["zsh"]